language: ruby
bundler_args: "--without production development"
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "cp config/setup_conf.yml.example config/setup_conf.yml"
script: bundle exec rake
rvm:
  - 2.1.2
