send_private_messages_notifications:
  every:
    - "30s"
  class: PrivateMessagesWorker
  description: "Sends notifications for all private messages not notified yet"

send_join_requests_notifications:
  every:
    - "30s"
  class: JoinRequestsWorker
  description: "Sends notifications for all join requests not notified yet"

send_invitations:
  every:
    - "30s"
  class: InvitationsWorker
  description: "Finds all invitations still not sent and sends them"

finish_meetings:
  every:
    - "30s"
  class: BigbluebuttonFinishMeetings
  description: "Checks for meetings that finished and mark as finished. Same as 'rake bigbluebutton_rails:meetings:finish'."

update_recordings:
  every:
    - "30m"
  class: BigbluebuttonUpdateRecordings
  description: "Gets the recordings in the server to populate the db. Same as 'rake bigbluebutton_rails:recordings:update'."
